export const links = [
  {
    id: 1,
    text: 'home',
    url: '/',
  },
  {
    id: 2,
    text: 'shipping',
    url: '/shipping',
  },
  {
    id: 3,
    text: 'products',
    url: '/products',
  },
]

export const surpriseMePrompts = [
  'A sleek leather sofa in a minimalist living room setting',
  'An antique mahogany dining table surrounded by vintage chairs in a classic dining room',
  'A plush velvet armchair in a chic, contemporary reading nook',
  'A rustic wooden coffee table in a cozy cabin-style living room',
  'A modern, glass-top desk in a bright and airy home office',
  'An elegant marble console table in a sophisticated entryway',
  'A comfortable bean bag chair in a fun and vibrant playroom',
  'A traditional oak bookshelf filled with books in a quiet study room',
  'A compact bistro table set on a small balcony overlooking the city',
  'A luxurious tufted headboard in a romantic and serene bedroom',
  'A mid-century modern sideboard in a retro-inspired dining area',
  'An industrial metal bar stool at a sleek kitchen island',
  'A contemporary L-shaped sectional in a spacious and open living space',
  'A minimalist floating shelf in a modern and streamlined bathroom',
  'A charming wicker chair in a sun-soaked conservatory filled with plants',
  'A vintage leather chesterfield sofa in a sophisticated gentleman’s lounge',
  'A bold geometric rug under a simple yet elegant coffee table in a contemporary living room',
  'A canopy bed draped with sheer fabrics in an exotic and dreamy bedroom',
  'A vibrant and colorful ottoman in a playful and eclectic living area',
  'A sleek and simple writing desk in a minimalist and focused home office',
  'A classic pedestal dining table in a formal and traditional dining room',
  'A pair of modern acrylic chairs in a sleek and futuristic kitchen',
  'A rustic farmhouse sink in a warm and inviting country-style kitchen',
  'A statement-making chandelier over a grand piano in an opulent music room',
  'A cozy window seat with soft cushions in a light-filled reading corner',
  'An ornate gilt mirror over a marble fireplace in an elegant living room',
  'A space-saving murphy bed in a compact and multifunctional studio apartment',
  'A luxurious freestanding bathtub in a spa-like and tranquil bathroom',
  'A set of colorful nesting tables in a dynamic and versatile living space',
  'A hanging rattan chair in a bohemian-styled sunroom filled with greenery',
  'An outdoor teak dining set on a spacious and inviting patio',
  'A sleek and modern entertainment unit in a high-tech home theater',
  'A cozy upholstered bench in a warm and welcoming entry hall',
  'A sculptural metal bookcase in a contemporary and artistic living room',
  'A minimalist Japanese-style platform bed in a serene and zen bedroom',
  'A chic glass coffee table in a modern and stylish living room',
  'A set of industrial pendant lights over a rustic kitchen island',
  'A bold and colorful modular sofa in a fun and playful family room',
  'A classic rocking chair in a quaint and cozy nursery',
  'A sophisticated wine rack in an elegant and well-appointed dining room',
  'A modernist sculptural chair in a minimalist and design-forward office',
  'A vintage trunk used as a coffee table in a travel-themed living room',
  'An oversized floor cushion in a casual and relaxed lounge area',
  'A stylish and functional kitchen cart in a small yet chic kitchen',
  'A luxurious velvet chaise lounge in a lavish and opulent dressing room'
];
